Numpy is used for mathematical operations (Array)

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
arr=np.array([1,2,3,4,5])*5
print(arr)

[ 5 10 15 20 25]


In [5]:
arr=np.array([1,2,3]*5)
print(arr)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [6]:
arr=[10,20,30,40]*2
print(arr,type(arr))

[10, 20, 30, 40, 10, 20, 30, 40] <class 'list'>


In [ ]:
arr=np.array([1,2,3,4,5],ndmin=2) # ndimn is used to define the Dimension of the array
print(arr,type(arr))

[[1 2 3 4 5]] <class 'numpy.ndarray'>


In [21]:
arr.ndim # -> Given 2 [[]]

2

In [26]:
arr=np.array([[1,2,3],[4,5,6]],ndmin=2) # Length of sublist should be same
print(arr)

[[1 2 3]
 [4 5 6]]


In [27]:
arr.shape

(2, 3)

In [ ]:
# range:

# print(list(range(1,10))) # list type

# It cant accept float values, we need to explicitly convert to list

# print(np.arange(1,10)) numpy array type

# It can accept float values, automatically convert it numpy array type

arr=np.arange(1,10)
arr_float=np.arange(1,11,1.5)

print(arr,type(arr))
print(arr_float,type(arr_float))
                                         

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[ 1.   2.5  4.   5.5  7.   8.5 10. ] <class 'numpy.ndarray'>


In [47]:
# linspace()

arr=np.linspace(1,10) # By default it distrubutes into 50 values
arr1=np.linspace(1,10,4) # it gives only 4 values as mentioned

# print(arr,type(arr))
print(arr1,type(arr1))

[ 1.  4.  7. 10.] <class 'numpy.ndarray'>


In [48]:
# Creating 2D array

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Indexing and Slicing

In [ ]:
# Indexing 
# We access the values by using +ve and -ve index
# If the index is not present it generates the error
# We can access the value by using step value also
# We can modify the values

In [49]:
# Syntax -> arrayname[rowindex,columnindex]
# [start:stop:step(row),start:stop:step(col)]

arr[0]

array([1, 2, 3])

In [50]:
arr[-1]

array([7, 8, 9])

In [52]:
# arr[-4]
# IndexError: index -4 is out of bounds for axis 0 with size 3

In [ ]:
arr[1,2]
# [[1 2 3]  row 0  col 0 1 2
# [4 5 6]   row 1  col 0 1 2
# [7 8 9]]  row 2  col 0 1 2

np.int64(6)

In [54]:
arr[2,2]

np.int64(9)

In [55]:
arr[0,1]

np.int64(2)

In [57]:
# Modifying

arr[0]=[11,22,33]
arr

array([[11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
# Slicing

arr[1:3,1:3] # [row slic :column slice]

# ([[11, 22, 33],
# [ 4,  5,  6],
# [ 7,  8,  9]])

# from row 1 to row 3 (3 will be excluded) row 1,row 2
# from column 1 to column 3 (3 will be excluded) column 1,column 2

array([[5, 6],
       [8, 9]])

In [ ]:
arr[0:2,1:3]
# Here column starts with 1 

array([[22, 33],
       [ 5,  6]])

In [63]:
arr[3:0,3:2]

array([], shape=(0, 0), dtype=int64)

In [64]:
arr

array([[11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [65]:
arr[0:2:,2:0:-1] # Giving -1 will reverse the value positions

array([[33, 22],
       [ 6,  5]])

random() 

It is a module inside this it has rand which is used to generate random values

In [ ]:
np.random.rand() # returns float

0.8577470890416184

In [73]:
np.random.randint(1,10) # It returns the value from range 1 to 10
# Returns integer values as we used randint()

5

In [75]:
arr=np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
arr.shape

(3, 2)

In [78]:
arr.flatten() # Flatten is used to return multiple lists in single list

array([1, 2, 3, 4, 5, 6])

In [ ]:
# reshape() (row,col)

arr.reshape(2,3) # 2 rows 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [82]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [83]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# resize() -> resize the original array

arr.resize(1,6) 
arr

array([[1, 2, 3, 4, 5, 6]])

In [86]:
arr.resize(6,1)
arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Variance and Covariance

In [88]:
x=np.array([10,20,30,40,50])
y=np.array([100,200,300,400,500])
n=len(x)
n

5

In [ ]:
var_x=np.sum((x-x.mean())**2)/n
# first it takes the mean of x and then it substracts the original x from mean x
# then it squares the x which is substracted from mean
# then it adds the values (sum)
# the it divide the values by n (len(n) = 5)
var_x

np.float64(200.0)

In [91]:
# Instead of doing all the steps just use var method
np.var(x)

np.float64(200.0)

In [92]:
var_y=np.sum((y-y.mean())**2)/n
var_y

np.float64(20000.0)

In [93]:
np.var(y)

np.float64(20000.0)